# SPDX-FileCopyrightText: 2023 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[tool.bumpversion]
current_version = "0.9.10"

[[tool.bumpversion.files]]
filename = "crates/scryptenc/README.md"

[[tool.bumpversion.files]]
filename = "crates/scryptenc/src/lib.rs"

[[tool.bumpversion.files]]
filename = "docs/book/modules/lib/pages/usage.adoc"
