# SPDX-FileCopyrightText: 2022 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "scryptenc"
version = "0.10.0"
edition.workspace = true
rust-version.workspace = true
description = "An implementation of the scrypt encrypted data format"
documentation = "https://docs.rs/scryptenc"
homepage.workspace = true
repository.workspace = true
license = "Apache-2.0 OR MIT"
keywords = ["crypto", "scrypt"]
categories = ["cryptography", "no-std"]
include = ["/LICENSES", "/README.md", "/src"]

[package.metadata.docs.rs]
all-features = true

[[example]]
name = "decrypt"
required-features = ["std"]

[[example]]
name = "encrypt"
required-features = ["std"]

[[example]]
name = "info"
required-features = ["serde", "std"]

[dependencies]
aes = "0.9.0"
ctr = "0.10.0"
hmac = "0.13.0"
scrypt = { version = "0.11.0", default-features = false }
serde = { version = "1.0.228", default-features = false, features = ["derive"], optional = true }
sha2 = { version = "0.11.0", default-features = false }

[dependencies.rand]
version = "0.8.6"
default-features = false
features = ["getrandom", "std_rng"]

[dev-dependencies]
anyhow.workspace = true
clap.workspace = true
dialoguer.workspace = true
serde_json = "1.0.149"
serde_test = "1.0.177"

[features]
default = ["std"]
alloc = []
serde = ["dep:serde"]
std = ["alloc", "scrypt/std"]

[lints]
workspace = true
