// SPDX-FileCopyrightText: 2022 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= rscrypt(1)
// Specify in UTC.
:docdate: 2025-05-11
:revnumber: 0.7.14
:doctype: manpage
:mansource: rscrypt {revnumber}
:manmanual: General Commands Manual
ifndef::site-gen-antora[:includedir: ./include]
:scrypt-url: https://www.tarsnap.com/scrypt.html

== NAME

rscrypt - an utility for encrypt and decrypt files

== SYNOPSIS

*{manname}* [_OPTION_]... _COMMAND_

== DESCRIPTION

*{manname}* is a command-line utility for encrypt and decrypt files using the
{scrypt-url}[scrypt encrypted data format].

== COMMANDS

*rscrypt-enc*(1)::

  Encrypt files.

*rscrypt-dec*(1)::

  Decrypt files.

*rscrypt-info*(1)::

  Provides information about the encryption parameters.

*rscrypt-completion*(1)::

  Generate shell completion.

*rscrypt-help*(1)::

  Print the help for a command.

== OPTIONS

*-h*, *--help*::

  Print help message. The short flag (*-h*) will print a condensed help message
  while the long flag (*--help*) will print a detailed help message.

*-V*, *--version*::

  Print version number. The long flag (*--version*) will also print the
  copyright notice, the license notice and where to report bugs.

ifndef::site-gen-antora[include::{includedir}/section-exit-status.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-exit-status.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-notes.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-notes.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-copyright.adoc[]]

== SEE ALSO

*scrypt*(1)
