// SPDX-FileCopyrightText: 2022 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= rscrypt-info(1)
// Specify in UTC.
:docdate: 2024-04-15
:doctype: manpage
ifdef::revnumber[:mansource: rscrypt {revnumber}]
ifndef::revnumber[:mansource: rscrypt]
:manmanual: General Commands Manual
:includedir: ./include

== NAME

rscrypt-info - provides information about the encryption parameters

== SYNOPSIS

*rscrypt info* [_OPTION_]... _FILE_

== DESCRIPTION

This command provides information about the encryption parameters. The result
will be write to stdout.

== POSITIONAL ARGUMENTS

_FILE_::

  Input file. If "-" is specified, data will be read from stdin.

== OPTIONS

ifdef::json,env-github,site-gen-antora[]
*-j*, *--json*::

  Output the encryption parameters as JSON.
endif::[]

*-h*, *--help*::

  Print help message. The short flag (*-h*) will print a condensed help message
  while the long flag (*--help*) will print a detailed help message.

*-V*, *--version*::

  Print version number. The long flag (*--version*) will also print the
  copyright notice, the license notice and where to report bugs.

include::{includedir}/section-exit-status.adoc[]

include::{includedir}/section-notes.adoc[]

== EXAMPLES

Print the encryption parameters:{blank}::

  $ *rscrypt info data.txt.scrypt*

ifdef::json,env-github,site-gen-antora[]
Print the encryption parameters as JSON:{blank}::

  $ *rscrypt info -j data.txt.scrypt*
endif::[]

include::{includedir}/section-reporting-bugs.adoc[]

include::{includedir}/section-copyright.adoc[]

== SEE ALSO

*rscrypt*(1), *rscrypt-dec*(1), *rscrypt-enc*(1), *rscrypt-help*(1), *scrypt*(1)
