// SPDX-FileCopyrightText: 2022 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= rscrypt-enc(1)
// Specify in UTC.
:docdate: 2024-08-02
:doctype: manpage
ifdef::revnumber[:mansource: rscrypt {revnumber}]
ifndef::revnumber[:mansource: rscrypt]
:manmanual: General Commands Manual
ifndef::site-gen-antora[:includedir: ./include]

== NAME

rscrypt-enc - encrypt files

== SYNOPSIS

*rscrypt enc* [_OPTION_]... _INFILE_ [_OUTFILE_]

== DESCRIPTION

This command encrypts _INFILE_ to _OUTFILE_. If _INFILE_ is "-", data will be
read from standard input. If _OUTFILE_ is not specified, the result will be
write to standard output.

The passphrase used for encryption can be read from either `/dev/tty`, standard
input, an environment variable, or a file.

== POSITIONAL ARGUMENTS

_INFILE_::

  Input file. If "-" is specified, data will be read from standard input.

_OUTFILE_::

  Output file. If _OUTFILE_ is not specified, the result will be write to
  standard output.

== OPTIONS

*-f*, *--force*::

  Force the decryption to proceed even if it requires an excessive amount of
  resources.

*-M*, *--max-memory* _BYTE_::

  Use at most the specified bytes of RAM to compute the derived key. _BYTE_ can
  also be provided as bytes with the unit symbol (such as MiB and GB). _BYTE_
  should be between 1 MiB and 16 EiB.

*-m*, *--max-memory-fraction* _RATE_::

  Use at most the specified fraction of the available RAM to compute the
  derived key. _RATE_ can be provided as a decimal or a fraction. _RATE_ should
  be greater than 0 and less than or equal to *0.5*. Default is 0.125.

*-t*, *--max-time* _DURATION_::

  Use at most the specified duration of CPU time to compute the derived key.
  Default is 5 seconds.

*--log-n* _VALUE_::

  Set the work parameter N to 2^_VALUE_. _VALUE_ should be between *10* and
  *40*. If this option is specified, *-r* and *-p* must also be specified.

*-r* _VALUE_::

  Set the work parameter r. _VALUE_ should be between *1* and *32*. If this
  option is specified, *--log-n* and *-p* must also be specified.

*-p* _VALUE_::

  Set the work parameter p. _VALUE_ should be between *1* and *32*. If this
  option is specified, *--log-n* and *-r* must also be specified.

*--passphrase-from-tty*::

  Read the passphrase from `/dev/tty`. This is the default behavior.

*--passphrase-from-stdin*::

  Read the passphrase from standard input. This option cannot be used if
  _INFILE_ is also standard input.

*--passphrase-from-tty-once*::

  Read the passphrase from `/dev/tty` only once.

*--passphrase-from-env* _VAR_::

  Read the passphrase from the environment variable. Note that storing a
  passphrase in an environment variable can be a security risk.

*--passphrase-from-file* _FILE_::

  Read the passphrase from the file. Note that storing a passphrase in a file
  can be a security risk.

*-v*, *--verbose*::

  Print encryption parameters and resource limits.

*-h*, *--help*::

  Print help message. The short flag (*-h*) will print a condensed help message
  while the long flag (*--help*) will print a detailed help message.

*-V*, *--version*::

  Print version number. The long flag (*--version*) will also print the
  copyright notice, the license notice and where to report bugs.

ifndef::site-gen-antora[include::{includedir}/section-exit-status.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-exit-status.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-notes.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-notes.adoc[]]

== EXAMPLES

Encrypt a file:{blank}::

  $ *rscrypt enc data.txt data.txt.scrypt*

Encrypt a file with the specified resource limits:{blank}::

  $ *rscrypt enc -M 512MiB -t 10s data.txt data.txt.scrypt*

Encrypt a file with the specified parameters:{blank}::

  $ *rscrypt enc --log-n 10 -r 1 -p 1 data.txt > data.txt.scrypt*

Read the passphrase from the specified file:{blank}::

  $ *rscrypt enc --passphrase-from-file passphrase.txt data.txt data.txt.scrypt*

Print encryption parameters and resource limits:{blank}::

  $ *rscrypt enc -v data.txt > data.txt.scrypt*

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-copyright.adoc[]]

== SEE ALSO

*rscrypt*(1), *rscrypt-dec*(1), *rscrypt-help*(1), *rscrypt-info*(1),
*scrypt*(1)
