// SPDX-FileCopyrightText: 2023 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= rscrypt-help(1)
// Specify in UTC.
:docdate: 2023-07-17
:revnumber: 0.7.14
:doctype: manpage
:mansource: rscrypt {revnumber}
:manmanual: General Commands Manual
ifndef::site-gen-antora[:includedir: ./include]

== NAME

rscrypt-help - print the help for a command

== SYNOPSIS

*rscrypt help* [_COMMAND_]

== DESCRIPTION

This command prints the help for a command.

This command is identical to any of the following:{blank}::

  $ *rscrypt* [_COMMAND_] *-h*|*--help*

== POSITIONAL ARGUMENTS

_COMMAND_::

  Subcommand to print the help.

ifndef::site-gen-antora[include::{includedir}/section-exit-status.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-exit-status.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-notes.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-notes.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-copyright.adoc[]]

== SEE ALSO

*rscrypt*(1), *rscrypt-dec*(1), *rscrypt-enc*(1), *rscrypt-info*(1), *scrypt*(1)
