// SPDX-FileCopyrightText: 2022 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= rscrypt-info(1)
// Specify in UTC.
:docdate: 2025-05-26
:revnumber: 0.8.1
:doctype: manpage
:mansource: rscrypt {revnumber}
:manmanual: General Commands Manual
ifndef::site-gen-antora[:includedir: ./include]
:ietf-datatracker: https://datatracker.ietf.org
:datatracker-html-doc: {ietf-datatracker}/doc/html
:rfc7914: {datatracker-html-doc}/rfc7914

== NAME

rscrypt-info - provides information about the encryption parameters

== SYNOPSIS

*rscrypt info* [_OPTION_]... _FILE_

== DESCRIPTION

This command provides information about the encryption parameters from _FILE_.
If _FILE_ is "-", data will be read from standard input.

The encryption parameters outputs either a human-readable string or JSON.

.List of the encryption parameters
|===
|Parameter |Description

|`N` (`costParameter`)
|The CPU/Memory cost parameter

|`r` (`blockSize`)
|The block size

|`p` (`parallelizationParameter`)
|The parallelization parameter
|===

The encryption parameters represents the same thing as the scrypt parameters as
defined in {rfc7914}[RFC 7914].

== POSITIONAL ARGUMENTS

_FILE_::

  Input file. If "-" is specified, data will be read from standard input.

== OPTIONS

*-j*, *--json*::

  Output the encryption parameters as JSON. This option is available if the
  `json` feature is enabled at compile time.

*-h*, *--help*::

  Print help message. The short flag (*-h*) will print a condensed help message
  while the long flag (*--help*) will print a detailed help message.

*-V*, *--version*::

  Print version number.

ifndef::site-gen-antora[include::{includedir}/section-exit-status.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-exit-status.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-notes.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-notes.adoc[]]

== EXAMPLES

Print the encryption parameters:{blank}::

  $ *rscrypt info data.txt.scrypt*

Print the encryption parameters as JSON:{blank}::

  $ *rscrypt info -j data.txt.scrypt*

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-copyright.adoc[]]

== SEE ALSO

*rscrypt*(1), *rscrypt-completion*(1), *rscrypt-dec*(1), *rscrypt-enc*(1),
*scrypt*(1)
