# SPDX-FileCopyrightText: 2022 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "scryptenc-wasm"
version = "0.3.0"
edition.workspace = true
rust-version.workspace = true
description = "Wasm bindings for scryptenc"
homepage.workspace = true
repository.workspace = true
license = "Apache-2.0 OR MIT"
keywords = ["crypto", "scrypt"]
categories = ["cryptography", "wasm"]
include = ["/LICENSES", "/README.md", "/src"]
publish = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["--enable-bulk-memory", "--enable-nontrapping-float-to-int"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
getrandom = { version = "0.2.16", features = ["js"] }
scryptenc = { path = "../scryptenc", version = "0.10.0" }
wasm-bindgen = "0.2.105"

[dev-dependencies]
wasm-bindgen-test = "0.3.55"

[lints]
workspace = true
