# SPDX-FileCopyrightText: 2022 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

name: CI

on:
  pull_request:
  push:
    branches:
      - "develop"
      - "master"
  schedule:
    - cron: "0 0 * * 0"

jobs:
  check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os-alias:
          - ubuntu
          - macos
          - windows
        toolchain-alias:
          - msrv
          - stable
        include:
          - os-alias: ubuntu
            os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - os-alias: macos
            os: macos-14
            target: aarch64-apple-darwin
          - os-alias: windows
            os: windows-2022
            target: x86_64-pc-windows-msvc
          - toolchain-alias: msrv
            toolchain: 1.85.0
          - toolchain-alias: stable
            toolchain: stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: ${{ matrix.target }}
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.8.0
        with:
          key: ${{ matrix.target }}
      - name: Check packages
        run: cargo check --target ${{ matrix.target }}
      - name: Check packages (no default features)
        run: cargo check --target ${{ matrix.target }} --no-default-features
      - name: Check packages (`alloc` feature)
        run: cargo check -p scryptenc --target ${{ matrix.target }} --no-default-features -F alloc
      - name: Check packages (`serde` feature)
        run: cargo check -p scryptenc --target ${{ matrix.target }} -F serde
      - name: Check packages (`serde` feature with no default features)
        run: cargo check -p scryptenc --target ${{ matrix.target }} --no-default-features -F serde

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os-alias:
          - ubuntu
          - macos
          - windows
        toolchain-alias:
          - msrv
          - stable
        include:
          - os-alias: ubuntu
            os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - os-alias: macos
            os: macos-14
            target: aarch64-apple-darwin
          - os-alias: windows
            os: windows-2022
            target: x86_64-pc-windows-msvc
          - toolchain-alias: msrv
            toolchain: 1.85.0
          - toolchain-alias: stable
            toolchain: stable
    steps:
      - name: Set Git to use LF
        if: matrix.os == 'windows-2022'
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: ${{ matrix.target }}
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.8.0
        with:
          key: ${{ matrix.target }}
      - name: Run tests
        run: cargo test -p scryptenc -p scryptenc-cli --target ${{ matrix.target }}
      - name: Run tests (no default features)
        run: cargo test -p scryptenc -p scryptenc-cli --target ${{ matrix.target }} --no-default-features
      - name: Run tests (`alloc` feature)
        run: cargo test -p scryptenc --target ${{ matrix.target }} --no-default-features -F alloc
      - name: Run tests (`serde` feature)
        run: cargo test -p scryptenc --target ${{ matrix.target }} -F serde
      - name: Run tests (`serde` feature with no default features)
        run: cargo test -p scryptenc --target ${{ matrix.target }} --no-default-features -F serde

  wasm-check:
    name: Check Wasm bindings
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        toolchain-alias:
          - msrv
          - stable
        include:
          - toolchain-alias: msrv
            toolchain: 1.85.0
          - toolchain-alias: stable
            toolchain: stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.8.0
      - name: Check a package
        run: wasm-pack build -s sorairolake -t nodejs --dev crates/wasm

  wasm-test:
    name: Test Wasm bindings
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        toolchain-alias:
          - msrv
          - stable
        include:
          - toolchain-alias: msrv
            toolchain: 1.85.0
          - toolchain-alias: stable
            toolchain: stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.8.0
      - name: Run tests
        run: wasm-pack test --node crates/wasm

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.8.0
      - name: Check code formatted
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.8.0
      - name: Check no lint warnings
        run: cargo clippy --workspace -- -D warnings
      - name: Check no lint warnings (no default features)
        run: cargo clippy --workspace --no-default-features -- -D warnings

  doc:
    name: Documentation
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.8.0
      - name: Check no `rustdoc` lint warnings
        run: RUSTDOCFLAGS="-D warnings" cargo doc --workspace --exclude scryptenc-cli --no-deps --document-private-items

  benchmark:
    name: Benchmark
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.8.0
      - name: Run benchmarks
        run: cargo bench -p scryptenc

  wasm-examples:
    name: Examples for the Wasm bindings
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.3
        with:
          deno-version: v2.x
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.8.0
      - name: Check code formatted
        run: deno fmt --check examples/*.ts
        working-directory: crates/wasm
      - name: Check no lint warnings
        run: deno lint examples/*.ts
        working-directory: crates/wasm
      - name: Build a package
        run: wasm-pack build -t deno crates/wasm
      - name: Type-check
        run: deno check examples/*.ts
        working-directory: crates/wasm
